#!/bin/sh

RESOLV_CONF=/tmp/resolv.conf

case "$1" in
        bound|renew)
                echo set IP $ip $subnet
                ifconfig $interface $ip netmask $subnet
                echo adding default route $router
                route add default gw $router
                for ii in $dns; do
                        echo adding nameserver $ii
                        echo nameserver $ii >> $RESOLV_CONF
                done
                # trigger dnsmasq restart
                kill -s SIGHUP `pidof dnsmasq`
                ;;
        deconfig)
                echo setting interface $interface to 0.0.0.0
                ifconfig $interface 0.0.0.0
                #ifconfig $interface down
                echo deleting $RESOLV_CONF
                echo -n > $RESOLV_CONF
                kill -s SIGHUP `pidof dnsmasq`
                ;;
esac
